#!/bin/bash
set -e

# Post-provision hook for Azure AI Foundry deployment
# Writes a .env file at the project root so presentation scripts can use it.

echo "Running post-provision hook..."

# Determine project root (three levels up from this script)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

# Read all outputs from the azd environment
AZURE_AI_PROJECT_ENDPOINT=$(azd env get-value AZURE_AI_PROJECT_ENDPOINT)
AI_PROJECT_NAME=$(azd env get-value AI_PROJECT_NAME)
AZURE_LOCATION=$(azd env get-value AZURE_LOCATION)
AZURE_RESOURCE_GROUP=$(azd env get-value AZURE_RESOURCE_GROUP)
AZURE_TENANT_ID=$(azd env get-value AZURE_TENANT_ID)
AZURE_AI_MODEL_DEPLOYMENT_NAME=$(azd env get-value AZURE_AI_MODEL_DEPLOYMENT_NAME)
AZURE_AI_IMAGE_MODEL_DEPLOYMENT_NAME=$(azd env get-value AZURE_AI_IMAGE_MODEL_DEPLOYMENT_NAME)

# Optional outputs – tolerate missing values
BING_PROJECT_CONNECTION_ID=$(azd env get-value BING_PROJECT_CONNECTION_ID 2>/dev/null || echo "")
BING_CONNECTION_NAME=$(azd env get-value BING_CONNECTION_NAME 2>/dev/null || echo "")

# Write .env at project root
ENV_FILE="$PROJECT_ROOT/.env"
cat > "$ENV_FILE" <<EOF
# Auto-generated by postprovision.sh – $(date -u +"%Y-%m-%dT%H:%M:%SZ")
AZURE_AI_PROJECT_ENDPOINT=$AZURE_AI_PROJECT_ENDPOINT
AI_PROJECT_NAME=$AI_PROJECT_NAME
AZURE_LOCATION=$AZURE_LOCATION
AZURE_RESOURCE_GROUP=$AZURE_RESOURCE_GROUP
AZURE_TENANT_ID=$AZURE_TENANT_ID
AZURE_AI_MODEL_DEPLOYMENT_NAME=$AZURE_AI_MODEL_DEPLOYMENT_NAME
AZURE_AI_IMAGE_MODEL_DEPLOYMENT_NAME=$AZURE_AI_IMAGE_MODEL_DEPLOYMENT_NAME
BING_PROJECT_CONNECTION_ID=$BING_PROJECT_CONNECTION_ID
BING_CONNECTION_NAME=$BING_CONNECTION_NAME
EOF

echo "✅ Azure AI Foundry deployment completed"
echo "   Resource Group: $AZURE_RESOURCE_GROUP"
echo "   Foundry Account: $AI_PROJECT_NAME"
echo "   Endpoint: $AZURE_AI_PROJECT_ENDPOINT"
echo "   Chat Model Deployment: $AZURE_AI_MODEL_DEPLOYMENT_NAME"
echo "   Image Model Deployment: $AZURE_AI_IMAGE_MODEL_DEPLOYMENT_NAME"
echo ""
echo "   .env written to: $ENV_FILE"
echo ""
echo "You can now run: python presentation.py .speckit/specifications/ai101.spec.md"

exit 0