# Post-provision hook for Azure AI Foundry deployment
# Writes a .env file at the project root so presentation scripts can use it.

$ErrorActionPreference = "Stop"

Write-Host "Running post-provision hook..."

# Determine project root (three levels up from this script)
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Resolve-Path (Join-Path $ScriptDir "..\..\..") | Select-Object -ExpandProperty Path

# Read all outputs from the azd environment
$AZURE_AI_PROJECT_ENDPOINT = azd env get-value AZURE_AI_PROJECT_ENDPOINT
$AI_PROJECT_NAME = azd env get-value AI_PROJECT_NAME
$AZURE_LOCATION = azd env get-value AZURE_LOCATION
$AZURE_RESOURCE_GROUP = azd env get-value AZURE_RESOURCE_GROUP
$AZURE_TENANT_ID = azd env get-value AZURE_TENANT_ID
$AZURE_AI_MODEL_DEPLOYMENT_NAME = azd env get-value AZURE_AI_MODEL_DEPLOYMENT_NAME
$AZURE_AI_IMAGE_MODEL_DEPLOYMENT_NAME = azd env get-value AZURE_AI_IMAGE_MODEL_DEPLOYMENT_NAME

# Optional outputs - tolerate missing values
try { $BING_PROJECT_CONNECTION_ID = azd env get-value BING_PROJECT_CONNECTION_ID } catch { $BING_PROJECT_CONNECTION_ID = "" }
try { $BING_CONNECTION_NAME = azd env get-value BING_CONNECTION_NAME } catch { $BING_CONNECTION_NAME = "" }

# Write .env at project root
$timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
$envFile = Join-Path $ProjectRoot ".env"
$envContent = @"
# Auto-generated by postprovision.ps1 - $timestamp
AZURE_AI_PROJECT_ENDPOINT=$AZURE_AI_PROJECT_ENDPOINT
AI_PROJECT_NAME=$AI_PROJECT_NAME
AZURE_LOCATION=$AZURE_LOCATION
AZURE_RESOURCE_GROUP=$AZURE_RESOURCE_GROUP
AZURE_TENANT_ID=$AZURE_TENANT_ID
AZURE_AI_MODEL_DEPLOYMENT_NAME=$AZURE_AI_MODEL_DEPLOYMENT_NAME
AZURE_AI_IMAGE_MODEL_DEPLOYMENT_NAME=$AZURE_AI_IMAGE_MODEL_DEPLOYMENT_NAME
BING_PROJECT_CONNECTION_ID=$BING_PROJECT_CONNECTION_ID
BING_CONNECTION_NAME=$BING_CONNECTION_NAME
"@

Set-Content -Path $envFile -Value $envContent -Encoding UTF8

Write-Host "`u{2705} Azure AI Foundry deployment completed"
Write-Host "   Resource Group: $AZURE_RESOURCE_GROUP"
Write-Host "   Foundry Account: $AI_PROJECT_NAME"
Write-Host "   Endpoint: $AZURE_AI_PROJECT_ENDPOINT"
Write-Host "   Chat Model Deployment: $AZURE_AI_MODEL_DEPLOYMENT_NAME"
Write-Host "   Image Model Deployment: $AZURE_AI_IMAGE_MODEL_DEPLOYMENT_NAME"
Write-Host ""
Write-Host "   .env written to: $envFile"
Write-Host ""
Write-Host "You can now run: python presentation.py .speckit/specifications/ai101.spec.md"

exit 0
